// HzDesktopShellExt.idl: HzDesktopShellExt 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(HzDesktopShellExt.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(ff7c8c69-789b-4985-ac8a-7559d77945ca),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IHzDesktopMenuExt : IDispatch
{
};
[
	uuid(c56958dd-a53f-4818-9307-bc345c50e9af),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{120b0821-767d-4654-9693-e4f9a7b4c0b3}")
]
library HzDesktopShellExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(120b0821-767d-4654-9693-e4f9a7b4c0b3)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(eed23024-9b96-4a84-afb6-a7e0c2cde7f5)
	]
	coclass HzDesktopMenuExt
	{
		[default] interface IHzDesktopMenuExt;
	};
};

import "shobjidl.idl";
